services:
  jupyter:
    build: ./jupyter
    container_name: jupyter_notebook
    user: root
    ports:
      - '8888:8888'
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/home/jovyan/data
    environment:
      JUPYTER_ENABLE_LAB: 'yes'
      CHOWN_HOME: 'yes'
      CHOWN_HOME_OPTS: '-R'